starter_kit : true
custom_recipes : true

prefix : "ยง7[MCZombies] "

# Disable or Enable items below
simple_bandage : true
advanced_bandage : true
grenade : true
molotov : true
# Item Settings
grenade_radius: 3
molotov_radius: 1